name: TMCz
main: com.themaskedcrusader.tmcz.Tmcz
version: Alpha 2.1.147.2
description: A Zombie Survival gamemode similar to MineZ/DayZ for bukkit Servers
author: masked_crusader
website: http://dev.bukkit.org/server-mods/tmc-zombie-smp/

commands:
    tmcz:
        description: Access to all TMCZ admin commands
    spawnz:
        description: Spawn into the TMCZ game
    diez:
        description: Commit suicide, return to world spawn
    killz:
        description: See your current Zombie/Player kills